sudo: required
services:
  - docker

script:
  - docker build -t dpowersnewg/aspnetcoreapp ./AspNetCoreApp
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dpowersnewg/aspnetcoreapp