sudo: required
services:
  - docker

before_install:
  - docker build -t dpowersnewg/aspcorenetapp ./AspNetCoreApp

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dpowersnewg/aspcorenetapp