version: "3.4"

services:
  redis:
    image: 'redis:latest'
  aspnetcoreapp:
    build:
      context: ./AspNetCoreApp
      dockerfile: ./Dockerfile.amd64
    ports:
      - '5000:80'
      - '64327'