version: "3.4"

services:
  redis:
    image: 'redis:latest'
  mongodb:
    image: 'mongo:latest'
  aspnetcoreapp:
    build:
      context: ./AspNetCoreApp
    ports:
      - '5000:80'
      - '64327'